spring:
  application:
    name: open-source
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  http://localhost:9090/realms/spring-api
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs